name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        env:
          DOCKER_USER:  ${{ secrets.DOCKER_USER }}
          DOCKER_PASS:  ${{ secrets.DOCKER_PASS }}
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          echo "Login exitoso a Docker Hub"

      - name: Build and Push Docker Image
        run: |
          docker build -t jormeno2020/electroautonomia:0.0.1 -t jormeno2020/electroautonomia:latest .
          docker push jormeno2020/electroautonomia:0.0.1
          docker push jormeno2020/electroautonomia:latest

  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/pronto

            echo "Deteniendo contenedores existentes..."
            docker-compose down

            echo "Eliminando imagen antigua..."
            docker rmi -f jormeno2020/electroautonomia:latest || true

            echo "Descargando última imagen..."
            docker-compose pull

            echo "Levantando nuevos contenedores..."
            docker-compose up -d

            echo "Esperando 10 segundos para que los contenedores arranquen..."
            sleep 10

            echo "Verificando el estado de los contenedores..."
            docker ps -a

            echo "Verificando logs del contenedor de la aplicación..."
            docker logs electro_front

            echo "Reiniciando Nginx Proxy (si es necesario)..."
            docker-compose restart nginx-proxy || true