name: Deploy to DigitalOcean

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        env:
          DOCKER_USER:  ${{ secrets.DOCKER_USER }}
          DOCKER_PASS:  ${{ secrets.DOCKER_PASS }}
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          echo "Login exitoso a Docker Hub"

      - name: Build Docker image
        run: |
          docker build -t jormeno2020/electroautonomia:0.0.1 -t jormeno2020/electroautonomia:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push jormeno2020/electroautonomia:0.0.1
          docker push jormeno2020/electroautonomia:latest

  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd pronto/
            git pull origin main
            docker-compose pull  # Descarga las últimas imágenes
            docker-compose down   # Detiene los contenedores antiguos
            docker-compose up -d  # Inicia los nuevos contenedores
            docker system prune -f  # Limpia imágenes antiguas