name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /ruta/del/proyecto
            git pull origin main
            docker-compose down   # Detiene los contenedores antiguos
            docker-compose up -d --build  # Construye y levanta los nuevos contenedores
            docker system prune -f  # Limpia contenedores e imágenes antiguas